/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package devint;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author -e-
 */
public class BR2 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    String s;
    Connection conn;
    PreparedStatement pst;
    
    public BR2() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jPanel3 = new javax.swing.JPanel();
        bookName = new javax.swing.JTextField();
        bookAuthor = new javax.swing.JTextField();
        bookCopies = new javax.swing.JTextField();
        bookISBN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Addbookbtn = new javax.swing.JButton();
        imgagelbl1 = new javax.swing.JLabel();
        Addbookcvrbtn = new javax.swing.JButton();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        closebtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1500, 1000));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setkEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookName.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        bookName.setForeground(new java.awt.Color(102, 102, 102));
        bookName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bookName.setText("Book Name");
        bookName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 102, 0)));
        bookName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        bookName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bookNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bookNameFocusLost(evt);
            }
        });
        jPanel3.add(bookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 320, 40));

        bookAuthor.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        bookAuthor.setForeground(new java.awt.Color(102, 102, 102));
        bookAuthor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bookAuthor.setText("Book Author");
        bookAuthor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 102, 0)));
        bookAuthor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bookAuthorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bookAuthorFocusLost(evt);
            }
        });
        jPanel3.add(bookAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 320, 40));

        bookCopies.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        bookCopies.setForeground(new java.awt.Color(102, 102, 102));
        bookCopies.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bookCopies.setText("Number of copies");
        bookCopies.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 102, 0)));
        bookCopies.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bookCopiesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bookCopiesFocusLost(evt);
            }
        });
        bookCopies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookCopiesActionPerformed(evt);
            }
        });
        jPanel3.add(bookCopies, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 320, 40));

        bookISBN.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        bookISBN.setForeground(new java.awt.Color(102, 102, 102));
        bookISBN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bookISBN.setText("Book ISBN");
        bookISBN.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 102, 0)));
        bookISBN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bookISBNFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bookISBNFocusLost(evt);
            }
        });
        bookISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookISBNActionPerformed(evt);
            }
        });
        jPanel3.add(bookISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 320, 40));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 652, 24, 24));

        Addbookbtn.setBackground(new java.awt.Color(255, 255, 255));
        Addbookbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devint/r/Addbook.png"))); // NOI18N
        Addbookbtn.setBorder(null);
        Addbookbtn.setBorderPainted(false);
        Addbookbtn.setContentAreaFilled(false);
        Addbookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbookbtnActionPerformed(evt);
            }
        });
        jPanel3.add(Addbookbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 690, 111, 87));

        imgagelbl1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 102, 0)));
        jPanel3.add(imgagelbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 260, 150));

        Addbookcvrbtn.setBackground(new java.awt.Color(255, 255, 255));
        Addbookcvrbtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Addbookcvrbtn.setText("Add Book Cover");
        Addbookcvrbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 102, 0)));
        Addbookcvrbtn.setContentAreaFilled(false);
        Addbookcvrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbookcvrbtnActionPerformed(evt);
            }
        });
        jPanel3.add(Addbookcvrbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 620, 131, 33));

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 204, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 51, 0));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Book Registration");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel4)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel3.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 38, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devint/r/panel2back.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 790));

        kGradientPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 420, -1));

        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devint/r/close.png"))); // NOI18N
        closebtn.setBorder(null);
        closebtn.setContentAreaFilled(false);
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        kGradientPanel2.add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, -10, -1, 100));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devint/r/previous.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 800, 90, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devint/r/backgroundnew.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        kGradientPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 850));

        jPanel2.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1355, 850));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bookNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookNameFocusGained
        // TODO add your handling code here:
        bookName.setText("");
    }//GEN-LAST:event_bookNameFocusGained

    private void bookAuthorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookAuthorFocusGained
        // TODO add your handling code here:
        bookAuthor.setText("");
    }//GEN-LAST:event_bookAuthorFocusGained

    private void bookCopiesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookCopiesFocusGained
        // TODO add your handling code here:
        bookCopies.setText("");
    }//GEN-LAST:event_bookCopiesFocusGained

    private void bookCopiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookCopiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookCopiesActionPerformed

    private void bookISBNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookISBNFocusGained
        // TODO add your handling code here:
        bookISBN.setText("");
    }//GEN-LAST:event_bookISBNFocusGained

    private void AddbookcvrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbookcvrbtnActionPerformed
       JFileChooser fileChooser = new JFileChooser();
         fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
         FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg","gif","png");
         fileChooser.addChoosableFileFilter(filter);
         int result = fileChooser.showSaveDialog(null);
         if(result == JFileChooser.APPROVE_OPTION){
             File selectedFile = fileChooser.getSelectedFile();
             String path = selectedFile.getAbsolutePath();
             imgagelbl1.setIcon(ResizeImage(path));
             s = path;
              }
         else if(result == JFileChooser.CANCEL_OPTION){
             System.out.println("No Data");
         }    
    }//GEN-LAST:event_AddbookcvrbtnActionPerformed
    
    public ImageIcon ResizeImage(String imgPath){
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(imgagelbl1.getWidth(), imgagelbl1.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }            
    
    
    private void bookNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookNameFocusLost
        // TODO add your handling code here:
        String adminname=bookName.getText();
        if(adminname.equals("")){
            bookName.setText("Book name");
        
        }
    }//GEN-LAST:event_bookNameFocusLost

    private void bookISBNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookISBNFocusLost
        // TODO add your handling code here:
        String adminnic = bookISBN.getText();
        if(adminnic.equals("")){
            bookISBN.setText("Book ISBN");
        }
    }//GEN-LAST:event_bookISBNFocusLost

    private void bookAuthorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookAuthorFocusLost
        // TODO add your handling code here:
        String adminaddress = bookAuthor.getText();
        if(adminaddress.equals("")){
            bookAuthor.setText("Book Author");
    }
    }//GEN-LAST:event_bookAuthorFocusLost

    private void bookCopiesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookCopiesFocusLost
        // TODO add your handling code here:
        String adminemail = bookCopies.getText();
        if(adminemail.equals("")){
            bookCopies.setText("Number of copies");
        }
    }//GEN-LAST:event_bookCopiesFocusLost

    private void AddbookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbookbtnActionPerformed
         String bookname = bookName.getText();
        String bookisbn = bookISBN.getText();
        String bookauthor = bookAuthor.getText();
        String bookcopies = bookCopies.getText();

        if (bookname.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fill Required fields");
        }
        else if (bookisbn.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fill Required fields");
        }
        else if (bookauthor.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fill Required fields");
        }
        else if(bookcopies.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fill Required fields");
        }
        else
        {
            String sql = "INSERT INTO book_registration (book_name, book_isbn, book_author, no_of_copies, book_image) VALUES (?,?,?,?,?)";
            try
            {
                pst = conn.prepareStatement(sql);
                InputStream is = new FileInputStream(new File(s));
                pst.setString(1, bookName.getText());
                pst.setString(2, bookISBN.getText());
                pst.setString(3, bookAuthor.getText());
                pst.setString(4, bookCopies.getText());
                pst.setBlob(5,is);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Successfully added!!");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
                
            }
            bookName.setText(null);
            bookISBN.setText(null);
            bookAuthor.setText(null);
            bookCopies.setText(null);
        }

        
    }//GEN-LAST:event_AddbookbtnActionPerformed

    private void bookISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookISBNActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closebtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        LibrarianMenue1 lb1 = new LibrarianMenue1();
        lb1.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BR2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BR2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BR2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BR2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BR2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbookbtn;
    private javax.swing.JButton Addbookcvrbtn;
    private javax.swing.JTextField bookAuthor;
    private javax.swing.JTextField bookCopies;
    private javax.swing.JTextField bookISBN;
    private javax.swing.JTextField bookName;
    private javax.swing.JButton closebtn;
    private javax.swing.JLabel imgagelbl1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    // End of variables declaration//GEN-END:variables
}
