/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package devint;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author -e-
 */
public class MR2 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Connection conn;
    PreparedStatement pst;
    String s;
    public MR2() {
        initComponents();
        conn = SQLCON.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jPanel3 = new javax.swing.JPanel();
        memberName = new javax.swing.JTextField();
        memberAddress = new javax.swing.JTextField();
        memberEmail = new javax.swing.JTextField();
        memberNIC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblimage = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jDate = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        closebtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1500, 1000));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setkEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        memberName.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        memberName.setForeground(new java.awt.Color(102, 102, 102));
        memberName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        memberName.setText("Member Name");
        memberName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 255)));
        memberName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        memberName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                memberNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                memberNameFocusLost(evt);
            }
        });
        jPanel3.add(memberName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 320, 40));

        memberAddress.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        memberAddress.setForeground(new java.awt.Color(102, 102, 102));
        memberAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        memberAddress.setText("Address");
        memberAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 255)));
        memberAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                memberAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                memberAddressFocusLost(evt);
            }
        });
        jPanel3.add(memberAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 320, 40));

        memberEmail.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        memberEmail.setForeground(new java.awt.Color(102, 102, 102));
        memberEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        memberEmail.setText("Email");
        memberEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 255)));
        memberEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                memberEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                memberEmailFocusLost(evt);
            }
        });
        memberEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberEmailActionPerformed(evt);
            }
        });
        jPanel3.add(memberEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 320, 40));

        memberNIC.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        memberNIC.setForeground(new java.awt.Color(102, 102, 102));
        memberNIC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        memberNIC.setText("Member NIC");
        memberNIC.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 255)));
        memberNIC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                memberNICFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                memberNICFocusLost(evt);
            }
        });
        jPanel3.add(memberNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 390, 320, 40));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 652, 24, 24));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devint/verify.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 703, 111, 87));

        lblimage.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 253)));
        jPanel3.add(lblimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 119, 233, 145));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton2.setText("Add Profile picture");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 253)));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 282, 131, 33));

        jDate.setBackground(new java.awt.Color(255, 255, 255));
        jDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 253)));
        jDate.setToolTipText("Date of Birth");
        jDate.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jDate.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jDateMouseEntered(evt);
            }
        });
        jPanel3.add(jDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 448, 320, 40));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Date Of Birth");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 494, -1, -1));

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 204, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 51, 0));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Member  Registration");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel4)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 38, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devint/r/panel2back.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 790));

        kGradientPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 420, -1));

        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devint/r/close.png"))); // NOI18N
        closebtn.setBorder(null);
        closebtn.setContentAreaFilled(false);
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        kGradientPanel2.add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, -20, -1, 100));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devint/r/previous.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 800, 90, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devint/r/backgroundnew.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        kGradientPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 850));

        jPanel2.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1355, 850));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void memberNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memberNameFocusGained
        // TODO add your handling code here:
        memberName.setText("");
    }//GEN-LAST:event_memberNameFocusGained

    private void memberAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memberAddressFocusGained
        // TODO add your handling code here:
        memberAddress.setText("");
    }//GEN-LAST:event_memberAddressFocusGained

    private void memberEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memberEmailFocusGained
        // TODO add your handling code here:
        memberEmail.setText("");
    }//GEN-LAST:event_memberEmailFocusGained

    private void memberEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberEmailActionPerformed

    private void memberNICFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memberNICFocusGained
        // TODO add your handling code here:
        memberNIC.setText("");
    }//GEN-LAST:event_memberNICFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       JFileChooser fileChooser = new JFileChooser();
         fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
         FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg","gif","png");
         fileChooser.addChoosableFileFilter(filter);
         int result = fileChooser.showSaveDialog(null);
         if(result == JFileChooser.APPROVE_OPTION){
             File selectedFile = fileChooser.getSelectedFile();
             String path = selectedFile.getAbsolutePath();
             lblimage.setIcon(ResizeImage(path));
             s = path;
              }
         else if(result == JFileChooser.CANCEL_OPTION){
             System.out.println("No Data");
         }    
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public ImageIcon ResizeImage(String imgPath){
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(lblimage.getWidth(), lblimage.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }            
    
    
    private void memberNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memberNameFocusLost
        // TODO add your handling code here:
        String adminname=memberName.getText();
        if(adminname.equals("")){
            memberName.setText("Username");
        
        }
    }//GEN-LAST:event_memberNameFocusLost

    private void memberNICFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memberNICFocusLost
        // TODO add your handling code here:
        String adminnic = memberNIC.getText();
        if(adminnic.equals("")){
            memberNIC.setText("NIC");
        }
    }//GEN-LAST:event_memberNICFocusLost

    private void memberAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memberAddressFocusLost
        // TODO add your handling code here:
        String adminaddress = memberAddress.getText();
        if(adminaddress.equals("")){
            memberAddress.setText("Address");
    }
    }//GEN-LAST:event_memberAddressFocusLost

    private void memberEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memberEmailFocusLost
        // TODO add your handling code here:
        String adminemail = memberEmail.getText();
        if(adminemail.equals("")){
            memberEmail.setText("Email");
        }
    }//GEN-LAST:event_memberEmailFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String membername = memberName.getText();
        String membernic = memberNIC.getText();
        String memberaddress = memberAddress.getText();
        String memberdob = jDate.getDateFormatString();
        String email = memberEmail.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("YYY-MM-DD");
        
        
        EmailValidator emailValidator = new EmailValidator();
        
        IdentyCardValidator identiyCardValidator = new IdentyCardValidator();
        
        //Sending Email creating the message body
            final String FromEmail = "bookhubworld69@gmail.com";
            final String FromEmailPassword = "cb007874";
            String Subjects = "Book Hub Library Management System";
           
           
           
            Properties properties = new Properties();
           
            properties.put("mail.smtp.starttls.enable","true");
            properties.put("mail.smtp.auth","true");
            properties.put("mail.smtp.host","smtp.gmail.com");
            properties.put("mail.smtp.port","587");
           
            Session session = Session.getDefaultInstance(properties, new javax.mail.Authenticator()
            {
                @Override
                protected PasswordAuthentication getPasswordAuthentication()
                {
                    return new PasswordAuthentication(FromEmail,FromEmailPassword);
                }
               
            });
        //_______________________________________
        
        if (membername.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fill Required fields");
        }
        else if (membernic.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fill Required fields");
        }
        else if (!identiyCardValidator.validate(membernic.trim()))
        {
            JOptionPane.showMessageDialog(null, "Input a valid ID number");
        }
        else if (memberaddress.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fill Required fields");
        }
        else if (memberdob.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fill Required fields");
        }
        else if(email.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fill Required fields");
        }
        else if (!emailValidator.validate(email.trim()))
        {
            JOptionPane.showMessageDialog(null, "Input Correct Email Format");
        }
        else
        {
            String memberDOB = sdf.format(jDate.getDate());
            String sql = "INSERT INTO member_registration (member_name,nic,address,dob,email,member_image) VALUES (?,?,?,?,?,?)";
            try 
            {
                pst = conn.prepareStatement(sql);
                InputStream is = new FileInputStream(new File(s));
                pst.setString(1, memberName.getText());
                pst.setString(2, memberNIC.getText());
                pst.setString(3, memberAddress.getText());
                pst.setString(4, memberDOB);
                pst.setString(5, memberEmail.getText());
                pst.setBlob(6,is);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Successfully Added!!");
                
                // JavaMail1.sendMail(email);
                MimeMessage message = new MimeMessage(session);
                message.setFrom(new InternetAddress(FromEmail));
                message.addRecipient(Message.RecipientType.TO, new InternetAddress(email));
                message.setSubject(Subjects);
                //message.setText();
                message.setText( "Dear "+membername+",\n" +
                        "\n" +
                        "Thank you for registering to Bookhub Library. Your registration and payment has been received.\n" +
                        "\n" +
                        "You registered with this email: " +email+"\n" +
                        "\n" +
                        "If you have any questions leading up to the event, feel free to reply to this email.\n" +
                        "\n" +
                        "We look forward to see you. \n" +
                        "\n" +
                        "Kind Regards,\n" +
                        "Event Staff\n" +
                        "bookhublibraries69@gmail.com");
                Transport.send(message);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        
        memberName.setText(null);
        memberNIC.setText(null);
        //memberDOB.setText(null);
        memberAddress.setText(null);
        memberEmail.setText(null);
        jDate.setDate(null);
        lblimage.setIcon(null);
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jDateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateMouseEntered

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closebtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        LibrarianMenue1 lb1 = new LibrarianMenue1();
        lb1.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MR2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MR2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MR2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MR2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MR2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closebtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lblimage;
    private javax.swing.JTextField memberAddress;
    private javax.swing.JTextField memberEmail;
    private javax.swing.JTextField memberNIC;
    private javax.swing.JTextField memberName;
    // End of variables declaration//GEN-END:variables
}
